Level Check LearnClassSpells
tswow/tswow pull request #434
Opened 2022-01-23 02:22 UTC by kaytotes

Closes https://github.com/tswow/tswow/issues/432

Adds an extra parameter to the LearnClassSpells function that allows to limit the spells rewarded from class quests to just those matching your current level. 

Example usage:

```ts
export function Main(events: TSEvents) {
    events.Player.OnLevelChanged((player, oldLevel) => {
        player.LearnClassSpells(true, true, true);
    });
}
```

With the above when playing as a Warrior and using `.levelup 1` in game you will _not_ learn spells such as Defensive Stance. With it set to false (the old default behaviour) it will teach them at level 2 even though they shouldn't "naturally" get them at that level.

2022-01-24 18:29 UTC, ihm-tswow reviewed
i think the name could be reflective that it's quest levels that are limited by this. `limitQuestsByLevel` or something

2022-01-24 18:32 UTC, ihm-tswow requested changes
- i think the name could be reflective that it's quest levels that are limited by this. `limitQuestsByLevel` or something

- this should use a default value, you do that by giving it a default value in the header and then setting it as `limitByLevel?: boolean` in the `global.d.ts`

@tswow-admin should this be on or off by default?

2022-01-24 20:34 UTC, kaytotes commented
@ihm-tswow Update the name as per your request and set a default value of off as that was the prior behaviour so this is less of a breaking change. 

However please feel free to deliberate on what the default should be. Personally I believe on may be the right call as the automatic spell learning from trainers part already limits by level due to the underlying TC checks.

2022-01-26 12:37 UTC, ihm-tswow commented
Yeah, I think it's best to have it behave like the trinitycore command and keep default behavior unchanged.

2022-01-26 12:37 UTC, merged